# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LSDemo_Blog' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LSDemo_Blog

  pod 'Masonry', '~> 1.0.2'

end
